echo Installing required packages...
sudo apt update && sudo apt install qemu qemu-system-x86 aria2 -y > aptlogs.txt
echo Downloading Ubuntu 22.04.3 ISO...
aria2c -x16 -s16 -oDVD.iso https://releases.ubuntu.com/22.04.3/ubuntu-22.04.3-desktop-amd64.iso > downloadlogs.txt
echo Downloading noVNC...
qemu-img create -f qcow2 disk.img 25G
git clone https://github.com/novnc/noVNC.git noVNC > gitlogs.txt
echo Starting VM...
qemu-system-x86_64 -m 10240 -hda disk.img -vnc 127.0.0.1:1 -boot c -usbdevice tablet -cdrom DVD.iso -netdev user,id=n1 -device e1000,netdev=n1 -enable-kvm & ./noVNC/utils/novnc_proxy --vnc localhost:5901 --listen 0.0.0.0:80
